### ISSUE TITLE
Updating the email shard

### ISSUE THREAD

**Issue by confact** [luckyframework/carbon_smtp_adapter#2]
email shard is updated for crystal 0.34.0

Now it gives a lot of deprecation warnings which can be annoying.

So update it, here is the email class for the new email shard version:
```crystal
require "email"
class Carbon::SmtpAdapter < Carbon::Adapter
  Habitat.create do
    setting host : String = "localhost"
    setting port : Int32 = 25
    setting helo_domain : String? = nil
    setting use_tls : Bool = true
    setting username : String? = nil
    setting password : String? = nil
  end

  def deliver_now(email : Carbon::Email)
    config = ::EMail::Client::Config.new(settings.host, settings.port, helo_domain: settings.helo_domain)
    config.use_auth(settings.username.not_nil!, settings.password.not_nil!) unless settings.username.nil? || settings.password.nil?
    config.use_tls(EMail::Client::TLSMode::STARTTLS) if settings.use_tls

    client = ::EMail::Client.new(config)
    #::EMail::Client.log_level = Log::Severity::Debug

    new_email = ::EMail::Message.new
    new_email.from email.from.address, email.from.name

    email.to.each do |to_address|
      new_email.to(to_address.address, to_address.name)
    end
    email.cc.each do |cc_address|
      new_email.cc(cc_address.address, cc_address.name)
    end
    email.bcc.each do |bcc_address|
      new_email.bcc(bcc_address.address, bcc_address.name)
    end

    email.headers.each do |key, value|
      new_email.custom_header(key, value)
    end
    new_email.subject email.subject
    new_email.message email.text_body
    new_email.message_html email.html_body

    client.start do
      send(new_email)
    end
  end
end
```

**Comment by oneiros** [comment]
Hi and thanks for giving this shard a try.

I am sorry, but I am not sure I follow. I have only given it a cursory glance but at least according to the API docs of the email shard, the alternative syntax I used should still be valid.

Also, the only deprecation warnings that I see when running the specs are related to the Logger deprecation in crystal 0.34 and originate from the devmail shard. I will try to get this fixed there.

What other deprecation warnings did you get?

**Comment by confact** [comment]
@oneiros it was only the logger one.

I recoded it to follow their recommended flow. If you think it will work, you can just update the shard dependency :) Not trying to be rude or anything.

I love your shard!

**Comment by peterhoeg** [comment]
This can presumably be closed, right?

**Comment by oneiros** [comment]
I guess so.
