### ISSUE TITLE
Latest version should be 0.2.0 and not 0.1.2

### ISSUE THREAD

**Issue by peterhoeg** [luckyframework/carbon_smtp_adapter#5]
Further to #4 version `0.1.2` has been tagged which should be `0.2.0` according to the README:

> The current plan is to track carbon's major and minor numbers, so that carbon_smtp_adapter 0.1.x is compatible with carbon 0.1.x and so on.

**Comment by oneiros** [comment]
Oops. You are absolutely right. Should have paid more attention to my own README :man_facepalming: 

Should be fixed now.
