### ISSUE TITLE
Upgrading to Email 0.7.0 fails to compile

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/carbon_smtp_adapter#7]
I tried to upgrade to the latest Email shard version, but specs failed to run:

```
❯ crystal spec 
Showing last frame. Use --error-trace for full trace.

In lib/email/src/email.cr:66:36

 66 | config = EMail::Client::Config.create(*args, **named_args)
                                     ^-----
Error: missing argument: helo_domain
```

**Comment by oneiros** [comment]
Thanks for bringing this up. Sadly, I am not currently using Crystal or Lucky in production anymore.

I will try to look into this at some point. It is a nice motivation to get into doing some crystal again. But I have no idea when I will get around to it.

If in the meantime anyone else would like to contribute, that would be great. And if someone is using this shard in production and would like to take over maintenance, that would be fine as well.

**Comment by peterhoeg** [comment]
I'm going to be using this in "production" shortly *but* for a personal project, not a business. Maybe we can transfer the project to the luckyframework organization?

**Comment by jwoertink** [comment]
@oneiros We'd be happy to take it if you'd like.

**Comment by oneiros** [comment]
> We'd be happy to take it if you'd like.

I would like that a lot!

**Comment by peterhoeg** [comment]
It's probably better you just transfer it to @jwoertink first as transferring to an org requires permissions to create repositories in that org.

I do realize that it's dickish to sit here telling people what to do on 2 projects I haven't contributed to........ Apologies.

**Comment by jwoertink** [comment]
Yeah, that works. You can just transfer to me @oneiros and I can move it to the Lucky org. I'm actually using this shard in production now anyway. :upside_down_face:

**Comment by oneiros** [comment]
@jwoertink Github will not let me transfer the project because you already have a fork with the same name. I guess you have to remove or rename your fork first.

**Comment by jwoertink** [comment]
Ok, I've deleted that.

**Comment by jwoertink** [comment]
Thanks for doing that @oneiros!
